Обновлен субмодуль toxcore

diff --git a/qbs-build b/qbs-build
--- a/qbs-build
+++ b/qbs-build
@@ -103,7 +103,9 @@ do
             exit 1
             ;;
         *)  # No more options
-            break
+            #break
+            echo "Error: Unknown option: $1" >&2
+            exit 1
             ;;
     esac
 done
